var courses = [
    {
      "id": 1,
      "name": "Leanne Graham",
      "course":"Learn HTML5 Programming From Scratch",
      "university":"Duke University",
      "img":"https://imgur.com/TnmHEtH.jpg",
      "fee":"9.99",
      "rating":"4.5",
      "student": "32000",
      "lecture" : "42",
      "time":"12 hours",
      "website": "hildegard.org"
    },
      
    {
      "id": 2,
      "name": "Ervin Howell",
      "course":"Real World Websites with HTML5 and CSS3",
      "university":"Duke University",
      "img":"https://imgur.com/gLxmCPK.jpg",
      "fee":"13.99",
      "rating":"4.7",
      "student": "25000",
      "lecture" : "32",
      "time":"12 hours 15 Minutes",
      "website": "hildegard.org"
    },
    {
      "id": 3,
      "name": "Chelsey Dietrich",
      "course":"Basic Javascript",
      "university":"Stanford University",
      "img":"https://imgur.com/ruaYHbO.jpg",
      "fee":"10.99",
      "rating":"4.9",
      "student": "1000",
      "lecture" : "12",
      "time":"3 hours",
      "website": "hildegard.org"
    },
    {
      "id": 4,
      "name": "Patricia Lebsack",
      "course":"Bootstrap 4 From Scratch With 5 Projects",
      "university":"Duke University",
      "img":"https://imgur.com/BRandWj.jpg",
      "fee":"13.99",
      "rating":"4.7",
      "student": "4000",
      "lecture" : "13",
      "time":"4 hours",
      "website": "hildegard.org"
    },
    {
      "id": 5,
      "name": "Chelsey Dietrich",
      "course":"Learn Python Programming",
      "university":"Duke University",
      "img":"https://imgur.com/3paYgVJ.jpg",
      "fee":"8.99",
      "rating":"4.9",
      "student": "5600",
      "lecture" : "21",
      "time":"7 hours",
      "website": "hildegard.org"
    },
    {
      "id": 6,
      "name": "Mrs. Dennis Schulist",
      "course":"Theory Of Computation",
      "university":"Duke University",
      "img":"https://imgur.com/8XN89Rg.jpg",
      "fee":"11.99",
      "rating":"4.7",
      "student": "32000",
      "lecture" : "42",
      "time":"12 hours",
      "website": "hildegard.org"
    },
    {
      "id": 7,
      "name": "Kurtis Weissnat",
      "course":"Therapeutic Art Life Coach Certification",
      "university":"IBM",
      "img":"https://imgur.com/Hf3KZqc.jpg",
      "fee":"7.99",
      "rating":"4.7",
      "student": "1100",
      "lecture" : "12",
      "time":"2 hours",
      "website": "hildegard.org"
    },
    {
      "id": 8,
      "name": "Nicholas Runolfsdottir V",
      "course":"Physics - Kinematics for High School",
      "university":"Duke University",
      "img":"https://imgur.com/m9chl8C.jpg",
      "fee":"14.99",
      "rating":"4.9",
      "student": "32000",
      "lecture" : "42",
      "time":"12 hours",
      "website": "hildegard.org"
    },
    {
      "id": 9,
      "name": "Glenna Reichert",
      "course":"Become a Probability & Statistics Master",
      "university":"Duke University",
      "img":"https://imgur.com/TVqh7jr.jpg",
      "fee":"9.99",
      "rating":"4.7",
      "student": "32000",
      "lecture" : "42",
      "time":"12 hours 15 Minutes",
      "website": "hildegard.org"
    },
    {
      "id": 10,
      "name": "Clementina DuBuque",
      "course":"Complete JavaScript",
      "university":"Duke University",
      "img":"https://imgur.com/m07m4EU.jpg",
      "fee":"15.99",
      "rating":"4.9",
      "student": "2000",
      "lecture" : "11",
      "time":"3 hours",
      "website": "hildegard.org"
    },
    {
      "id": 11,
      "name": "John Doe",
      "course":"Photography MasterClass",
      "university":"Duke University",
      "img":"https://imgur.com/vO7hpl3.jpg",
      "fee":"8.90",
      "rating":"4.7",
      "student": "32000",
      "lecture" : "42",
      "time":"12 hours",
      "website": "hildegard.org"
    }
    ,
    {
      "id": 12,
      "name": "Kayra Topa",
      "course":"DSLR - Masterclass",
      "university":"Stanford",
      "img":"https://imgur.com/HE0CsA9.jpg",
      "fee":"11.99",
      "rating":"4.7",
      "student": "1000",
      "lecture" : "6",
      "time":"2 hours",
      "website": "hildegard.org"
    },
    {
      "id": 13,
      "name": "Jaggi",
      "course":"Artificial Intelligence - Machine Learning",
      "university":"IBM",
      "img":"https://imgur.com/ND5NE3N.jpg",
      "fee":"13.99",
      "rating":"4.7",
      "student": "32000",
      "lecture" : "42",
      "time":"12 hours",
      "website": "hildegard.org"
    }
    ,
    {
      "id": 14,
      "name": "Amu",
      "course":"Learning Business ",
      "university":"Duke University",
      "img":"https://imgur.com/tUPBKl8.jpg",
      "fee":"7",
      "rating":"4.7",
      "student": "1500",
      "lecture" : "12",
      "time":"5 hours",
      "website": "hildegard.org"
    },
    {
      "id": 15,
      "name": "Clementina DuBuque",
      "course":"Self Teaching",
      "university":"Duke University",
      "img":"https://imgur.com/UWlPYAc.jpg",
      "fee":"11",
      "rating":"4.7",
      "student": "1000",
      "lecture" : "32",
      "time":"2 hours",
      "website": "hildegard.org"
    }
  ];
  export default courses;